### ISSUE TITLE
2.1.2.2 Port mismatch

### ISSUE THREAD

**Issue by KuhlTime** [hs-duesseldorf/se2rest#2]
[2.1.2.2 Install Docker and set up the container in Windows and MacOS](https://github.com/hs-duesseldorf/se2rest#2122-install-docker-and-set-up-the-container-in-windows-and-macos)

@Feichtmeier could you change the port mapping of the docker container from port `8086` to port `80`. Otherwise the students will not be able to access phpmyadmin as described in [2.2. Setup user, database and permission](https://github.com/hs-duesseldorf/se2rest#22-setup-user-database-and-permission)

```bash
docker run -e TZ=Europe/Berlin --detach --tty -p 8086:80 -p 3306:3306 --name xamppy-docker --mount "source=xamppy-docker-vol,destination=/opt/lampp/var/mysql/" cswl/xampp
```

to

```bash
docker run -e TZ=Europe/Berlin --detach --tty -p 80:80 -p 3306:3306 --name xamppy-docker --mount "source=xamppy-docker-vol,destination=/opt/lampp/var/mysql/" cswl/xampp
```

**Comment by Feichtmeier** [comment]
What's the default port if you install xampp via installer locally?

**Comment by KuhlTime** [comment]
The default is port `80`.
